### ISSUE TITLE
Other HTTP verbs?

### ISSUE THREAD

**Issue by chris-hailstorm** [nameko/nameko#335]
Is there an intention to support PUT, PATCH and DELETE?

In addition to the current GET and POST.

Thank you

**Comment by davidszotten** [comment]
i believe the `method` argument is passed straight to werkzeug, so those probably just work

**Comment by gianchub** [comment]
Hello, 

a friend of mine had the same issue. His boss (non extremely tech person) was discarding nameko thinking that it isn't capable of handling requests other than GET and POST. So my friend did some digging, discovered Werkzeug is used internally, and therefore concluded nameko handles the other methods as well.

It would probably be very good to add a note in the documentation to point this out, so that people aren't discouraged by this.

Cheers,
fab

**Comment by mattbennett** [comment]
Indeed the other HTTP verbs do just work. I will make a note to update the docs!

**Comment by davidszotten** [comment]
been thinking we should be saying something like "nameko web is powered by werkzeug, the same wsgi library that underpins flask"

can also change the heading from "HTTP GET & POST" to just "HTTP"

**Comment by chris-hailstorm** [comment]
Awesome, thank you

**Comment by mattbennett** [comment]
The docs for this have now been updated thanks to @geoffjukes
