### ISSUE TITLE
What happens with the message if the service fails?

### ISSUE THREAD

**Issue by julianogouveia** [nameko/nameko#387]
Hi, i have a doubt. 

What happens with the rabbitmq message if the service fails for some reason? There is any way of process the message again? Or yet, after a specific number of tries the messages goes to the dead letter queue? There is any way to control or do that is Nameko? If not, you guys have a plan to implement this in the future?

Thanks.

**Comment by mattbennett** [comment]
The AMQP entrypoints (`@rpc`, `@event_handler` and `@consume`) all guarantee "at least once" delivery. This is the case because they acknowledge the message only _after_ it's been processed -- i.e. after the service method exits.

If the connection to the broker is lost (if the service crashes, for example, or any other reason) any outstanding "un-ack'd" messages go back to being "ready", meaning they can be processed by another consumer. This is where "at least once" comes from -- the message _will_ be picked up by a second worker, but there's no way to know whether it was successfully processed by the first worker or not.

Messages are acknowledged when the worker completes, irrespective of whether the worker returned a normal response or raised an exception. The `@event_handler` and `@consume` entrypoints have an additional `requeue_on_error` flag; if this is set, messages resulting in worker exceptions are requeued. This is sometimes useful but can be dangerous if you don't combine it with checks to make sure messages don't end up in an infinite loop.

RabbitMQ unfortunately does not support the "max deliveries" message property, but you can implement something like it yourself.

This kind of question is better suited to the [mailing list](https://groups.google.com/forum/#!forum/nameko-dev). If you have followup questions please ask them there, and I'll close this issue.
