### ISSUE TITLE
Make dispatching events from outside the nameko context nicer.

### ISSUE THREAD

**Issue by rollokb** [nameko/nameko#402]
Currently it is easy to make RPC calls from outside the context of a Nameko worker via the `ClusterRPCProxy`. However it is not as simple to fire events via the `event_dispatcher`.

Right now I need to pass in a basic Nameko config object, and (please correct me if I am wrong) a new connection to RabbitMQ is made with each dispatch.

Perhaps `nameko.standalone.events.event_dispatcher` could be decomposed into something that doesn't require a Nameko configuration to be passed in, and wasn't responsible for it's own connection so one could advantage of connection pooling.

**Comment by mattbennett** [comment]
I guess you figured this out already, but connections are pooled by kombu.

The API to the standalone dispatcher isn't wonderful, particularly having to pass in the "nameko config" object -- because actually all it needs is the AMQP URI and the serializer to use. I have a WIP branch that cleans up the AMQP publishers to some extent, so hopefully this will change soon.
