### ISSUE TITLE
Does nameko support load balancing?

### ISSUE THREAD

**Issue by erhuabushuo** [nameko/nameko#416]
Does nameko support load balancing?

**Comment by davidszotten** [comment]
Hi,

It depends a bit on what entrypoint you are using. For nameko (amqp) rpc, multiple instances of the same service will be load balanced by the rabbitmq broker.

If you use the http entrypoints, you need to put a load balancer in front of your services to distribute traffic.

In general it depends on the implementation of the entrypoint.

For future reference, please direct general questions to the mailing list instead of the issue tracker: https://groups.google.com/forum/#!forum/nameko-dev

**Comment by erhuabushuo** [comment]
Thanks a lot

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/does-nameko-support-load-balancing/313
