### ISSUE TITLE
WorkerContext for standalone rpc

### ISSUE THREAD

**Issue by scarchik** [nameko/nameko#439]
Hi @mattbennett,

I use standalone rpc to communicate between Flask front-end service with Nameko microservices. And I previously inherit WorkerContext to add unique request_id to each request. It needing to ensure better log investigating. My code:

```
class WorkerContextWithRequestID(WorkerContext):

    @property
    def context_data(self):
        data = self.data.copy()

        data[CALL_ID_STACK_CONTEXT_KEY] = [getattr(request, 'request_id')]
        data[CALL_ID_STACK_CONTEXT_KEY].extend(self.call_id_stack)

        return data
```

As I see it persistent context_data dictionary can't provide the same functionality.
WorkerContext had been deleted from standalone rpc in https://github.com/nameko/nameko/commit/1e2e3298a5e6ca05cd8cef3ae89ef4ef6f7c0c82.

Can we return WorkerContext to StandaloneProxyBase?

**Comment by mattbennett** [comment]
Using a custom `WorkerContext` class has been deprecated since Nameko 2.4.0. I don't really want to bring it back.

The use of a `WorkerContext` object in the standalone RPC proxy is strange anyway. It only exists to satisfy the "fake" ContainerFactory that is used there, which in turn only exists to help re-use code from the non-standalone RPC implementation.

You pass the `context_data` into the proxy when you instantiate it. Unfortunately there's no way to specify it per-call. You could implement a context manager that does it though:

``` python
def request_context(proxy):
    # modify the context data
    proxy._worker_ctx.context_data['request_id'] =  request.request_id
    yield
    # undo the modification
    del proxy._worker_ctx.context_data['request_id']

rpc_proxy = ClusterRpcProxy(config)

with request_context(rpc_proxy):
    rpc_proxy.foo.bar()  # use proxy
```

If the context manager is too messy, you could subclass the `ClusterRpcProxy` to always insert the request context.

You may also want to look at https://github.com/clef/flask-nameko, which might be nicer and/or easier to modify to your requirements.

**Comment by scarchik** [comment]
Thanks for your answer.

Unfortunately request_context is not working for me, because I use ClusterRpcProxy as global variable in multi threading environment.

In my project I need use API Gateway in front nameko microservices. For this task I should ensure that on Gateway I have less is better connections to RabbitMQ. In high load systems create new connections for each call is wasteful. In this case flask-nameko is not resolve connections issue.

As I see it for "standalone app & nameko" we don't need any pool of ClusterRpcProxy's but need have asynchronous Queue Consumer as nameko services use itself. I already write it and now testing: https://github.com/fraglab/nameko-proxy. Please look.

I can save overriding WorkerContext for me only, but it is better to have fair opportunity to do this.

**Comment by mattbennett** [comment]
I'm not a flask expert, but isn't the `request` object a thread-local? In that case, even a globally shared proxy object would be able to access the request object for a given execution. In that case, I would expect the `request_context` above to work.

The issue I have with overriding the `WorkerContext` in this case is that I don't like having to specify a worker context to a standalone RPC proxy at all. It is only used to extract the headers for the outbound message, and there is a better way to do that. The current design is a lazy way to reuse code in the `MethodProxy`.

We deprecated custom `WorkerContext` classes because you can also specify custom `ServiceContainer` classes, which should be enough for most use-cases, since the service container instantiates the worker context in most cases anyway. The exception is the RPC proxy, which is a mis-design.

I think it's fine for you to continue to solve the problem for "you only" for the time being. A better general design for the RPC proxy would allow you to easily set context data at proxy call time, not just definition time.
