### ISSUE TITLE
Publishing an event throws  amqp.exceptions.FrameSyntaxError if worker_ctx.data values are not strings.

### ISSUE THREAD

**Issue by wearp** [nameko/nameko#458]
worker_ctx.data dict must contain values of type `str`, otherwise when an event is published an `amqp.exceptions.FrameSyntaxError` is raised.

This is caused by the contents of `worker_ctx.data` eventually being used as headers in the published message: 

A potential solution would be to filter out those which aren't of correct type, [which is already done with `None` types](https://github.com/nameko/nameko/blob/9d00c232c0c336d93b30151b864717a113797a1d/nameko/messaging.py#L42). Or alternatively do some validation when a key is added to `worker_ctx.data`. 

Happy to submit a PR.

**Comment by mattbennett** [comment]
Oh interesting, thanks. I had assumed that kombu serialized them using whatever encoder is configured, but I guess not. A PR would be great!

Actually the warning about `None` values is kinda unhelpful because it tends to generate a lot of logs. Something that warned _once_ would probably be good (using the `warnings` module) or otherwise just dropping them silently.
