### ISSUE TITLE
call_async result

### ISSUE THREAD

**Issue by geoffjukes** [nameko/nameko#459]
Hi,

I'm looking at bridging/exposing my nameko services to a PHP application. ~~The 2 options I have come up with are a rest service (either a dedicated flask service, or directly using the http extension) or a Celery based worker (using php-celery).~~ -- Celery requires Kombu 4, which Nameko is not compatible with. So a REST service seems like my only option.

I'm open to other solutions, so please feel free to recommend an alternative approach. I kinda feel like adding additional layers to the stack detracts from the elegance of the Nameko solution. 

I am using Nameko to handle processing of multiple audio files. I have a master task that uses concurrent.futures.map to create a worker pool, each firing an RPCProxy task. As they come back, the master task updates some data, until they all return. The audio processing is an all-or-nothing situation, so a single failed subtask means the whole job failed. The master task marshals all the subtasks and reacts accordingly. The processing can take a few seconds, or many minutes (20+) depending on the length of the source audio, the number of files, and the type of processing. 

Originally I had this written in Celery, but the 'noise' from all the subtasks was insane, and made reporting/monitoring a nightmare. Nameko really fit the purpose, as I only really care about the master task, not the individual file tasks - failures etc are logged to Graylog2 for diagnostic and troubleshooting. 

So is there an easy way to submit that master task using call_async, and then check its status/result at a later date using a reference ID or something?

With Celery I can call a task, get the task ID, and use that at any time to check the task status (and in RPC mode, get the result exactly once). 

I guess an alternative idea might be to use call_async, and rely on event notifications to get results/status feedback. 

Anyway, not really a bug, but I've read the documentation and the code, and can't really figure it out. 

Many thanks for any help or advice. 

Geoff

**Comment by mattbennett** [comment]
Hi Geoff,

There's nothing out of the box that provides the kind of "task distribution" that Celery does I'm afraid, but there are plenty of lower-level tools to implement something like it.

To make sure I understand the request here, you want to kick off some potentially long-running request, and then later _from a different worker_ check whether it's completed yet and/or fetch the result?

To implement this you'd need somewhere to store the shared state and a way of serializing the task results in and out of it. The storage would contain some kind of empty or status value for each "in-flight" request, and the results for (recently) completed tasks. If the storage was shared you could have the task executors write their status/results to it, otherwise that could happen when the result was returned to the "master" task.

**Comment by geoffjukes** [comment]
Hi Matt,

Thanks for the response. Your understanding is correct, and your solution makes absolute sense.

One frustration with Celery was related to task deduplication. I have a Couchbase cluster handy 😄, and so I could use a distributed lock (like Sherlock) to prevent duplicate tasks, then a result store using a predictable key format. Storing results (as you say) from the "master" task. 

I like it. Thanks for the help!

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/call-async-result/309
