### ISSUE TITLE
why heartbeat param not in amqp.get_producer 

### ISSUE THREAD

**Issue by ornoone** [nameko/nameko#473]
this is a question to understand why the heartbeat feature is not used for all connections.

in fact, we found out that our very small micro-service stack (5 micro-services) was consuming more and more memory of our small rabbitmq server (> 400mb ) for 1 message every minutes.

we found out that more connection (which consume around 16Mb each) was created over the time, without being closed. the «stale» connections was without heartbeat.

I investigated to find that nameko was opening $max_woker connections to the rabbitmq during medium load via get_produced function, but these connections was without the heartbeat parameters, and was not closed after use.

I just ask if this is intended, or if this should be reworked.

after some experiment, it seem the add of heartbeat for get_producer remove the extra connection after the load has passed and thus the memory used by rabbitmq is lower for a small cluster of services.

version for testing: 

nameko latest master (commit 286d141af2e0fe3fc5b592228c4cea93ca495d81)
amqp==1.4.9

RabbitMQ 3.6.10, Erlang 19.3

**Comment by mattbennett** [comment]
Kombu (the library we use to send and receive AMQP messages) only supports heartbeats for consumer connections. Publishers use a pool of connections managed by Kombu, and at least within Nameko there's no mechanism to regularly send the heartbeats down these connections (unlike the consumers, which have a thread each).

You can probably improve your memory consumption by [limiting the size of the pools](http://docs.celeryproject.org/projects/kombu/en/latest/userguide/pools.html#setting-pool-limits).

By adding the `heartbeat` parameter to `get_producer` you're probably configuring the underlying connection with a heartbeat, but never actually sending the beat from the client side. The server will close the connection after two heats are missed, which is probably why you get your memory back. It's very inefficient though, since every connection lives for a maximum of `2 * heartbeat` seconds.

Ultimately I'd love to support heartbeats for publisher connections, but we'd need to replace kombu with a better AMQP library to do so.

**Comment by ornoone** [comment]
Ok, I was expecting something like that. 
we will work on the pool size instead

thanks to you for this very helpful response. I hope I will be of some use for this project one day :D

**Comment by epetrovich** [comment]
How to solve the dead TCP connections problem then? 
Rabbitmq documentation says to use heartbeats for all connections. We see a lot of dead connections when producers connect/disconnect.
https://www.rabbitmq.com/heartbeats.html

**Comment by mattbennett** [comment]
@epetrovich the ultimate solution is to replace kombu, which actually in progress now. No promises on when it will land though.

In the mean time, you shouldn't see _that_ many dead connections assuming you're using the kombu pools (which nameko does most of the time). What is "a lot" and what problems occur as a result?

**Comment by alexeysofin** [comment]
@mattbennett Is there some branch to see the progress? By the way what do you think about allowing to override get_producer here https://github.com/nameko/nameko/blob/master/nameko/amqp/publish.py#L175, which will allow to set some heartbeat to producer connection and thus will help rabbitmq close idle producers connections (as far as i understand if pool sees a broken connection it will release it and create a new one)?

**Comment by epetrovich** [comment]
Our producers are running on AWS spots for batch scheduled jobs. 
We can launch and shot down about 200-500 spot instances  per day. 
One working day adds about 2-3k dead connections from producers. We are working on graceful shutdown of rabbitmq producers also.

**Comment by alexeysofin** [comment]
@mattbennett we found our problem regarding too many dead connections. We just did not shutdown supervisor gracefully when terminating spot instances. But still it would be a nice feature to have producer heartbeat separate from consumer heartbeat (which might be None by default keeping backward compatibility). I personally do not like the workaround with inheriting from `PublisherCore` because I will have to copy-paste the whole `PublisherCore.publish` method, because there is no way to override `get_producer` inside it. Producer heartbeat although has no application (until there is an implementation supporting producer heartbeats) except for RabbitMQ will have a chance to clean up dead connections after a timeout, so maybe adding a support to supply connection kwargs though Producer class is not bad. What do you think?

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/why-heartbeat-param-not-in-amqp-get-producer/306
