### ISSUE TITLE
Question - nameko with alternative Kombu transports (Redis)

### ISSUE THREAD

**Issue by shauns** [nameko/nameko#474]
Hey guys -- just wondering if you've heard of any nameko use with Kombu transports other than RabbitMQ/AMQP, and specifically [Redis](http://docs.celeryproject.org/projects/kombu/en/latest/userguide/connections.html#transport-comparison).

Presumably(!) leaning on Kombu means things should be transport agnostic, but would be great to hear if anyone has had success in production.

**Comment by mattbennett** [comment]
Hey Shaun,

It's very unlikely this would work. We used Kombu because it seemed like the best AMQP library at the time, rather than to be transport agnostic. We rely on certain bits of AMQP and even make use of certain RabbitMQ extensions to the spec.

One of my longstanding desires is actually to remove kombu for one of the newer AMQP libs, so we can support things like publisher heartbeats.

**Comment by shauns** [comment]
Okay, well that's good to know before I went too far down the rabbit hole (pun intended)

**Comment by jacohend** [comment]
I need to second this...I've found rabbitmq to be very unreliable at scale, especially when paired with modern cluster orchestration (swarm, kubernetes). Would much prefer a redis broker.

**Comment by mattbennett** [comment]
Nameko is an extensible framework. There's no reason you couldn't [create a set of extensions](http://nameko.readthedocs.io/en/latest/writing_extensions.html) that implemented Nameko RPC or Events over Redis. The built-in versions are AMQP implementations though, and it would not be worth trying to make them work over a different transport, even with kombu in the middle.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/question-nameko-with-alternative-kombu-transports-redis/288
