### ISSUE TITLE
Check if rabbitmq available before running the service to prevent app crash

### ISSUE THREAD

**Issue by ivaschenko** [nameko/nameko#490]
Hello,

We encountered an issue while using Nameko in our project. I know that if Nameko service is running and at some point it looses connection with rabbit, it will try to re-establish connection numerous amount of times, and web server will be alive so we will be able to check the status. But if after lets say re-deploy something went wrong and Nameko is not able to connect to rabbit (something happened to it and it is unavailable) at 0 point, Nameko just crashes and we can't check the status in our deployment scripts... Is there any way to avoid this crash upon starting the service?Maybe some hook to run webserver first, and then try to connect and initialize queues so we can track what exactly happened?  
@mattbennett @davidszotten

**Comment by mattbennett** [comment]
Nameko will refuse to start if it can't connect to the AMQP broker, in the same way that a webserver won't start if it can't bind to the port you've given it. It's not really a crash.

Nameko is a framework. You can write services that use the bundled extensions that talk AMQP, HTTP, both or neither. It doesn't make sense for Nameko to start one type of extensions before the other... because it doesn't know what extensions are in use or what the requirements are.

The best way to solve your problem is probably to run the service behind something like supervisord, and restart the process if it fails to come up for some reason.
