### ISSUE TITLE
Why nameko did not use something like JSON RPC for serialization?

### ISSUE THREAD

**Issue by worldmind** [nameko/nameko#516]
As I understood after reading questions #455 and #354 (not found info in docs) nameko use own, non standard, calls serialization to json.
On my opinion it make difficult using nameko in heterogeneous environments, for example yesterday on by.pycon.org I ask @tarekziade why in Mozilla they write REST microservices, and answer was because they using not only python.

**Comment by mattbennett** [comment]
The main reason is that Nameko started out as a compatibility library for Openstack's Nova RPC protocol.

Nameko has evolved into a _framework_ now though, and you can [write your own extensions](http://nameko.readthedocs.io/en/stable/writing_extensions.html#writing-entrypoints). It would not be much code to add a set of extensions that did JSON-RPC if that's what you need.

The "built-in" extensions like AMQP-RPC are included in the main library because they're battle-tested and most historical Nameko installations use them.

**Comment by worldmind** [comment]
[gRPC](https://grpc.io/docs/guides/) sounds interesting too

**Comment by kooba** [comment]
@worldmind gRPC is very interesting indeed. We are very early in process of exploring feasibility of adding client/server gRPC extensions to Nameko. gRPC relies on HTTP2 and maybe with the help of [h2](https://github.com/python-hyper/hyper-h2/tree/master/examples/eventlet) library this would be possible. 

If you look at current official gRPC python support, workflow that is accomplished via statically generated stub (via C core lib) leaves lots to desire. Maybe Nameko implementation could provide simpler, more pythonic approach to creating gRPC services. But again it is very early and the scope is unknown at the moment.

**Comment by gpkc** [comment]
@kooba How is support for gRPC going?

**Comment by kooba** [comment]
@gpkc nothing to report yet.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/why-nameko-did-not-use-something-like-json-rpc-for-serialization/312
