### ISSUE TITLE
Trying to run two instances of rabbitMQ for Nameko.

### ISSUE THREAD

**Issue by sammy200592** [nameko/nameko#552]
Hi Matt,

I tried the method you suggested on the link
<https://github.com/nameko/nameko/issues/498>

I did this:
**AMQP_URI: amqp://guest:guest@localhost:562/;amqp://guest:guest@localhost:5672/**

This works fine when my first port address is set to the correct port i.e 5672 **but** it gives me an **error** when the **first port is wrong** and the **second port is right** just like in the case above.

I am trying this for the Nameko service and getting the following error:
**OSError: [Errno 61] ECONNREFUSED**

**Comment by mattbennett** [comment]
Nameko is telling you that it can't connect to RabbitMQ at `localhost:562`, presumably because it's not running on that port.

What are you expecting to happen here?

**Comment by sammy200592** [comment]
i want that if the first port is not present then nameko should connect with the second port provided so that the service does not go down.

**Comment by mattbennett** [comment]
OK, I see what you're getting at. You're trying to configure High Availability for RabbitMQ but without using a load-balancer.

When you provide an AMQP_URI containing two addresses, Nameko will connect to each address in a round-robin fashion, which is an alternative to using a load-balancer *if you target the individual nodes of a cluster*.

The problem you're running into is that Nameko will only round-robin when it **reconnects**. Because the first node is down when the service starts, it does not retry. This is a disadvantage of the round-robin approach.

If you make the _second_ URI the one that's broken you'll find that Nameko connects and the service runs until it loses connection with the first node; at this point it will try to connect to the second one, and retry until it succeeds.

**Comment by davidszotten** [comment]
that sounds like a strange (and undesirable) behaviour to me. is it a nameko design decision? what are the reasons for it?

**Comment by mattbennett** [comment]
No, it's kombu. We pass the connection string straight through.

See http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.connection.html#connection

> Parameters: |  URL (str, Sequence) – Broker URL, or a list of URLs.

**Comment by sammy200592** [comment]
Awesome Matt.
This is what I also understood by my research. 
Thanks a lot for clarifying the doubts though.

**Comment by mattbennett** [comment]
This issue was moved to https://discourse.nameko.io/t/trying-to-run-two-instances-of-rabbitmq-for-nameko/307
