### ISSUE TITLE
why rpc and timer can't work together in direct running in module

### ISSUE THREAD

**Issue by wyattsuen** [nameko/nameko#567]
I have met a strange problem, and test many times. I'm sure this is a bug, but how to solve it?
when the code is following, and run it with command line 'nameko run module', the timer runs normally. But when I run it with command line 'python module.py', the timer doesn't work.

```
class ServiceA:
    name='service_a'
    
    @rpc
    def dosomething(self):
        return 'hello world'

    @timer(interval=1)
    def daemon(self):
        print('ping')

if __name__=='__main__':  
    runner=ServiceRunner(config={'AMQP_URI': 'pyamqp://guest:guest@localhost'})
    runner.add_service(ServiceA)
    runner.start()
    runner.wait()
```

And If I run following code, no matter 'nameko run module' or 'python module.py', the timer runs normally.

```
class ServiceA:
    name='service_a'

    @timer(interval=1)
    def daemon(self):
        print('ping')

if __name__=='__main__':  
    runner=ServiceRunner(config={'AMQP_URI': 'pyamqp://guest:guest@localhost'})
    runner.add_service(ServiceA)
    runner.start()
    runner.wait()
```

So can anyone help solving it?

**Comment by mattbennett** [comment]
You're missing an `eventlet.monkey_patch`. See the note at the bottom of [this section](https://nameko.readthedocs.io/en/stable/key_concepts.html?highlight=monkey#service-runner) of the docs. `nameko run` applies this for you.

It happens to work in the timer-only case because that particular extension doesn't do any I/O, so doesn't need the eventlet patch to be applied.
