### ISSUE TITLE
Config method get doesn't exist

### ISSUE THREAD

**Issue by amitza** [nameko/nameko#604]
Hey,

I'm using nameko 2.11.0 with python 3.7 and I'm trying to read custom config value from the .yml file according to the documentation:

config = Config()

But the method config.get() doesn't exist. 

How do I do this?

**Comment by mattbennett** [comment]
If your `Config` is the built-in [DependencyProvider](http://docs.nameko.io/en/stable/built_in_dependency_providers.html#config), then it must be used inside a service method (as per the linked docs). Outside a service `config = Config()` will give you  the`DependencyProvider` instance and not the _dependency_ that it injects into the service.

You might want to take a look at the prerelease of Nameko 3 (`pip install --pre nameko`) because it adds a global helper that gives you access to the config. In Nameko 3 you can do simply:

``` python
from nameko import config

config.get('whatever')
```

The pull request which added this functionality is https://github.com/nameko/nameko/pull/520
