### ISSUE TITLE
How to make rabbitmq send a message to nameko service only once

### ISSUE THREAD

**Issue by 75509151** [nameko/nameko#634]

**Comment by mattbennett** [comment]
RabbitMQ doesn't _send_ messages at all -- the Nameko AMQP entrypoints _consume_ them.

In normal operation, each message will be consumed from a queue only once. However, if the connection to RabbitMQ is lost for any reason before the message is acknowledged (for example because the service died, was killed, or experienced a network failure) then the message will be returned to the queue and re-delivered to the next available consumer.

Messages are acknowledged only after the entrypoint has completed, so the delivery guarantee is "at least once". This is a fundamental part of the AMQP entrypoints.

Different delivery guarantees are possible if you acknowledge messages immediately ("at most once") but this comes with other tradeoffs and is not the approach taken by Nameko's AMQP entrypoints.
