### ISSUE TITLE
handle_result signature mess

### ISSUE THREAD

**Issue by litnimax** [nameko/nameko#660]
I am trying to use handle_result from the service:
```
    @bus('test')
    def bus_test(self, message):
        logger.debug('BUS TEST received: %s', message)
        return {'result': 'here'}
```
Now in my BusEventHandler(Entrypoint) class I have:
```
    def handle_result(self, message, worker_ctx, result, exc_info=None):
        logger.debug('Result message: %s, result: %s, worker: %s, exc: %s',
                     message, result, worker_ctx, exc_info)
```
And here is what I get:
```
BUS TEST received: {'msg': 'This is a test'}
Result message: <WorkerContext [odoo_broker.bus_test] at 0x7fb4df66c610>, result: None, worker: {'result': 'here'}, exc: None
```
As you may note result is passed in worker argument. 
I think I found the issue.
Pls look at the screenshot - https://imgur.com/a/XZhTZzV
Thanks for your attention.

**Comment by mattbennett** [comment]
It is inconsistent that `RpcConsumer.handle_result` has a slightly different signature from the other methods called `handle_result` in the built-in extensions, but unless you're extending `RpcConsumer` I don't think this is the cause of your problem.

Can you share the source for your `BusEventHandler`?

**Comment by litnimax** [comment]
Hi Matt!
Thanks for your response.
It's here - https://github.com/litnimax/nameko-odoo
So bus poller and rpc clients each keep own connection.
Thanks for looking.

P.S. BTW, this is a part of a crazy project :-) Inspired by Nameko I decided to rewrite my product Asterisk Management UI for Odoo (see http://odoo.com) on Nameko. So I implemented nameko-ami (https://github.com/litnimax/nameko-ami) and nameko-odoo.
And suddenly I realized that I can have all AMI messages (Asterisk core event bus) calling Odoo controllers so that Odoo can react on any.
This architecture allowed me to rewrite all previous functionality (features & demo here - https://www.odoo.com/apps/modules/12.0/asterisk_base/) .... only in Odoo. 
This means that every Odoo developer can program 95% of his call center for example.
And there are thousands of Odoo developers in the world that can start building beautiful telephony applications!
This is very exciting :-P

**Comment by mattbennett** [comment]
Hi @litnimax,

The problem is simply that `BusEventHandler.handle_result()` has an incorrect signature. It is expecting

```
def handle_result(self, message, worker_ctx, result, exc_info=None):
    ...
``` 

whereas the `ServiceContainer` callback does not pass the `message` object:

https://github.com/nameko/nameko/blob/9461e4800f0352de590af0667acc1d7001a946b8/nameko/containers.py#L403-L408

Notice that the RPC entrypoint, which you have used as inspiration, passes a `partial` when it calls `ServiceContainer.spawn_worker()`:

https://github.com/nameko/nameko/blob/9461e4800f0352de590af0667acc1d7001a946b8/nameko/rpc.py#L160-L164

If you want to receive the `message` object in `BusEventHandler.handle_result()` you should follow the same pattern.
